"""add categorys table

Revision ID: b6d8863fb3e0
Revises: ce5e829e779a
Create Date: 2019-12-25 15:00:10.706333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d8863fb3e0'
down_revision = 'ce5e829e779a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_created_time'), 'categories', ['created_time'], unique=False)
    op.create_index(op.f('ix_categories_modified_time'), 'categories', ['modified_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_modified_time'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_time'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
